services:
    relay-server:
        build:
            context: .
            dockerfile: containers/Dockerfile
        stop_grace_period: 1s
        ports:
            - "8080:8080"
        volumes:
            - .:/usr/src/app
