services:
    relay-server:
        build:
            context: .
            dockerfile: containers/production.Dockerfile
        container_name: relay-server-container
        stop_grace_period: 1s
        ports:
            - "8080:8080"
